---
- name: install and start apache
  hosts: all
#  become: yes
  vars:
    http_port: 80
    max_clients: 200

  tasks:
  - name: Deploy Apache
    yum:
      name: httpd
      state: installed
#  - name: install httpd
#    yum: name=httpd state=present
#  - name: write the apache config file
#    copy: src=/templates/index.html dest=/var/www/html/ mode=0644
  - name: start httpd
    systemd: name=httpd state=started

  - name: ensure apache is running (and enable it at boot)
    systemd: name=httpd state=started enabled=yes

  - firewalld:
      service: https
      permanent: true
      state: enabled

  - firewalld: port=80/tcp zone=public permanent=true state=enabled immediate=yes
