---
- name: This sets up an httpd webserver
  hosts: all
  tasks:
  - name: install httpd
    yum: name=nginx state=present
#  - name: write the apache config file
#    copy: src=/templates/index.html dest=/var/www/html/ mode=0644
  - name: start httpd
    systemd: name=httpd state=started
  - name: start firewall
    firewalld: service=https permanent=true state=enabled
  - name: open firewall
    firewalld: port=80/tcp zone=public permanent=true state=enabled immediate=yes
